registry-srv:
  image: registry:2
  ports:
    - 127.0.0.1:5000:5000
  volumes:
    - ./conf/registry-srv.yml:/etc/docker/registry/config.yml:ro
    - ./conf/auth.cert:/etc/docker/registry/auth.cert:ro

registry-web:
  image: hyper/docker-registry-web
  links:
    - registry-srv
  ports:
    - 0.0.0.0:8080:8080
  volumes:
    - ./conf/registry-web.yml:/conf/config.yml:ro
    - ./conf/auth.key:/conf/auth.key
    - /db:/data
